# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENe_9cwiijdjs7A1mVwsoi22BHLe1fZG
"""

image_files = ['https://imoges.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8ZmFjZXxlbnwwfHwwfHw%3D&w=1000&q=80.jpg','image1.jpg', 'https://www.park56dental.com/wp-content/uploads/2021/10/60bdfb41-68ae-469d-80e0-157ffdfd5167.jpg','image2.jpg', 'image3.jpg','image4.jpg',"noface.jpg",'https://img.freepik.com/premium-photo/child-smiles-shows-jagged-teeth-dental-medicine-healthcare_395106-2.jpg?w=2000.jpg',"https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8ZmFjZXxlbnwwfHwwfHw%3D&w=1000&q=80.jpg",] #input file


images = {name: cv2.imread(name) for name in image_files}
outcome=[]

for name, image in images.items():
  try:
    if name[:4] == "http":
      response = urllib.request.urlopen(name)
      image_data = response.read()
      image = cv2.imdecode(np.frombuffer(image_data, np.uint8), cv2.IMREAD_UNCHANGED)
      resized_image = cv2.resize(image, (1024, 1024))
      result = tooth_detector(resized_image)
      outcome.append(result)

    else:
      resize_and_show(image)
      result = tooth_detector(image)
      outcome.append(result)
  except Exception as e:
     outcome.append("False")





print(outcome)